### ISSUE TITLE
Failed to resolve ../../config.json on Windows 11 (64-bit)

### ISSUE THREAD

**Issue by imguest24897** [computernewb/collab-vm-1.2-webapp#104]
Log:
> cvmwebapp@2.0.0 build
> parcel build --no-source-maps --dist-dir dist --public-url '.' src/html/index.html

(node:2096) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
× Build failed.

@parcel/core: Failed to resolve '../../config.json' from './src/ts/main.ts'

  C:\Users\guest24897\collab-vm-1.2-webapp\src\ts\main.ts:3:20
    2 | import VM from './protocol/VM.js';
  > 3 | import Config from '../../config.json';
  >   |                    ^^^^^^^^^^^^^^^^^^^
    4 | import { Permissions, Rank } from './protocol/Permissions.js';
    5 | import { User } from './protocol/User.js';

@parcel/resolver-default: Cannot load file '../../config.json' in './src/ts'.
ℹ Did you mean '../../tsconfig.json'?
ℹ Did you mean '../../package.json'?

Any help, please?

**Comment by elijahr2411** [comment]
You need to copy `config.example.json` to `config.json` and fill the relevant fields. It should build after that.

**Comment by imguest24897** [comment]
> You need to copy `config.example.json` to `config.json` and fill the relevant fields. It should build after that.

Oh, I forgot, sorry 😅

**Comment by CatGames22817** [comment]
Why me say this error?
F:\collab-vm-win64 (21)\collab-vm-1.2-webapp-master>npm run build

> cvmwebapp@2.0.0 build
> parcel build --no-source-maps --dist-dir dist --public-url '.' src/html/index.html

× Build failed.

@parcel/core: Failed to resolve '../../../collab-vm-1.2-binary-protocol/src/index.js' from
'./src/ts/protocol/CollabVMClient.ts'

  F:\collab-vm-win64 (21)\collab-vm-1.2-webapp-master\src\ts\protocol\CollabVMClient.ts:14:70
    13 | // TODO: Properly workspaceify this
  > 14 | from '../../../collab-vm-1.2-binary-protocol/src/index.js';
  >    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    15 | const w = window as any;
    16 |

@parcel/resolver-default: Cannot load file '../../../collab-vm-1.2-binary-protocol/src/index.js' in './src/ts/protocol'.
ℹ Did you mean '../../../collab-vm-1.2-binary-protocol'?
ℹ Did you mean '_../../../node_modules/@parcel/cache/src/index.js_'?
