### ISSUE TITLE
Build failed even after yarn and npm install

### ISSUE THREAD

**Issue by SkyHighSundae** [computernewb/collab-vm-1.2-webapp#107]
It just gives me this:
@parcel/core: Failed to resolve 
'../../../collab-vm-1.2-binary-protocol/src/index.js' from 
'./src/ts/protocol/CollabVMClient.ts'

  /home/runner/StarryKookyRuby/collab-vm-webapp/src/ts/protocol/CollabVMClient.ts:14:70
    13 | // TODO: Properly workspaceify this
  > 14 | from '../../../collab-vm-1.2-binary-protocol/src/index.js';
  >    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    15 | const w = window as any;
    16 | 

@parcel/resolver-default: Cannot load file 
'../../../collab-vm-1.2-binary-protocol/src/index.js' in 
'./src/ts/protocol'.
💡 Did you mean '../../../collab-vm-1.2-binary-protocol'?
💡 Did you mean '_../../../node_modules/natural-compare/index.js_'?

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MDMCK10** [comment]
You likely forgot to download submodules, try the following command then build again:
`git submodule update --init --recursive`

**Comment by SkyHighSundae** [comment]
Thanks! It worked
