### ISSUE TITLE
The userlist's dropdown menu shows inside the userlist, when it should be outside of it

### ISSUE THREAD

**Issue by Undefishin** [computernewb/collab-vm-1.2-webapp#20]
Self-explanatory. The dropdown menu code needs to be changed to make it spawn outside of the user list instead of inside of it. Also, when you hover over the dropdown menu, the whole menu gets highlighted (and also the parent user item along with it).

**Comment by elijahr2411** [comment]
Do you know of a way to make the dropdown menu behave in the way you're describing?
