### ISSUE TITLE
Cannot read properties of null (reading 'connect')

### ISSUE THREAD

**Issue by Pikterra32** [computernewb/collab-vm-1.2-webapp#89]
Spamming entering a VM and immediately leaving back to home can cause this pop-up to show.

![image](https://github.com/computernewb/collab-vm-1.2-webapp/assets/131165383/a69024a0-47ec-4a5b-a911-6a162df00a81)

**Comment by Pikterra32** [comment]
It prob have to do with line 439 in main.ts

**Comment by elijahr2411** [comment]
Then don't do that
